# SERVER
server.port=8081
server.servlet.context-path=/

# THYMELEAF
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.mode=HTML
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# API BASE URL
api.base.url=http://localhost:8080/api

# LOGGING
logging.level.br.ufscar.dc.compraevenda.client=DEBUG
